import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { api, TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ 
  children: React.ReactNode,
  modal: React.ReactNode,
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bn bg-[#FFF8F3]">
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
        <Navbar/>
      </body>
    </html>
  );
}
